version: '3.9'
services:
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - task_network
  app-db:
    image: postgres
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    networks:
      - task_network
    restart: unless-stopped
networks:
  task_network:
    driver: bridge
volumes:
  postgres:
    driver: local